# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from typing import Optional
from typing_extensions import Literal

from ..._models import BaseModel

__all__ = ["OutputAudioDeltaEvent"]


class OutputAudioDeltaEvent(BaseModel):
    """An audio chunk generated by the Live model.

    Decode and play primary WebSocket chunks in delivery order using the configured session audio format. Sideband connections receive reflected output audio with timestamps.
    """

    delta: str
    """Base64-encoded raw audio.

    Primary WebSocket events use the session's configured format; reflected sideband
    events use mono PCM16LE at 24 kHz.
    """

    type: Literal["session.output_audio.delta"]
    """The event type, always `session.output_audio.delta`."""

    end_ms: Optional[int] = None
    """Exclusive session-relative end in milliseconds.

    Required on reflected sideband events; omitted on the primary WebSocket. Dropped
    output frames leave gaps between reflected ranges.
    """

    start_ms: Optional[int] = None
    """Inclusive session-relative start in milliseconds.

    Required on reflected sideband events; omitted on the primary WebSocket.
    """
