# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from typing import Dict, List, Union, Optional
from typing_extensions import Literal, Annotated, TypeAlias

from ..._utils import PropertyInfo
from ..._models import BaseModel
from .function_tool import FunctionTool

__all__ = [
    "ResponsesDelegationUpdateConfig",
    "Reasoning",
    "Text",
    "Tool",
    "ToolWebSearch",
    "ToolFileSearch",
    "ToolCodeInterpreter",
    "ToolShell",
    "ToolShellEnvironment",
    "ToolShellEnvironmentContainerAuto",
    "ToolShellEnvironmentContainerAutoNetworkPolicy",
    "ToolShellEnvironmentContainerAutoNetworkPolicyDisabled",
    "ToolShellEnvironmentContainerAutoNetworkPolicyAllowlist",
    "ToolShellEnvironmentContainerAutoSkill",
    "ToolShellEnvironmentContainerAutoSkillSkillReference",
    "ToolShellEnvironmentContainerAutoSkillInline",
    "ToolShellEnvironmentContainerAutoSkillInlineSource",
    "ToolShellEnvironmentContainerReference",
    "ToolShellEnvironmentLocal",
    "ToolShellEnvironmentLocalSkill",
    "ToolImageGeneration",
    "ToolMcp",
    "ToolCustom",
    "ToolNamespace",
    "ToolSearch",
    "ToolProgrammaticToolCalling",
    "ToolComputer",
    "ToolApplyPatch",
]


class Reasoning(BaseModel):
    """Reasoning settings passed to each delegated Responses request."""

    effort: Optional[Literal["none", "minimal", "low", "medium", "high", "xhigh"]] = None
    """How much reasoning effort the delegated Responses model should use.

    Supported values depend on the backend model.
    """

    summary: Optional[Literal["concise", "detailed", "auto"]] = None
    """
    The reasoning summary to request from the delegated Responses model, when
    supported.
    """


class Text(BaseModel):
    """Text generation settings passed to each delegated Responses request."""

    verbosity: Optional[Literal["low", "medium", "high"]] = None
    """The amount of detail in text generated by the Responses backend.

    This does not configure the Live model’s spoken delivery.
    """


class ToolWebSearch(BaseModel):
    """A web search tool available to the Live session’s Responses backend."""

    type: Literal["web_search"]
    """The tool type. Always `web_search`."""


class ToolFileSearch(BaseModel):
    type: Literal["file_search"]


class ToolCodeInterpreter(BaseModel):
    type: Literal["code_interpreter"]


class ToolShellEnvironmentContainerAutoNetworkPolicyDisabled(BaseModel):
    type: Literal["disabled"]
    """Disable outbound network access. Always `disabled`."""


class ToolShellEnvironmentContainerAutoNetworkPolicyAllowlist(BaseModel):
    allowed_domains: List[str]
    """A list of allowed domains when type is `allowlist`."""

    type: Literal["allowlist"]
    """Allow outbound network access only to specified domains. Always `allowlist`."""


ToolShellEnvironmentContainerAutoNetworkPolicy: TypeAlias = Annotated[
    Union[
        ToolShellEnvironmentContainerAutoNetworkPolicyDisabled,
        ToolShellEnvironmentContainerAutoNetworkPolicyAllowlist,
        None,
    ],
    PropertyInfo(discriminator="type"),
]


class ToolShellEnvironmentContainerAutoSkillSkillReference(BaseModel):
    skill_id: str
    """The ID of the referenced skill."""

    type: Literal["skill_reference"]
    """References a skill created with the /v1/skills endpoint."""

    version: Optional[str] = None
    """Optional skill version. Use a positive integer or 'latest'. Omit for default."""


class ToolShellEnvironmentContainerAutoSkillInlineSource(BaseModel):
    """Inline skill payload"""

    data: str
    """Base64-encoded skill zip bundle."""

    media_type: Literal["application/zip"]
    """The media type of the inline skill payload. Must be `application/zip`."""

    type: Literal["base64"]
    """The type of the inline skill source. Must be `base64`."""


class ToolShellEnvironmentContainerAutoSkillInline(BaseModel):
    description: str
    """The description of the skill."""

    name: str
    """The name of the skill."""

    source: ToolShellEnvironmentContainerAutoSkillInlineSource
    """Inline skill payload"""

    type: Literal["inline"]
    """Defines an inline skill for this request."""


ToolShellEnvironmentContainerAutoSkill: TypeAlias = Annotated[
    Union[ToolShellEnvironmentContainerAutoSkillSkillReference, ToolShellEnvironmentContainerAutoSkillInline],
    PropertyInfo(discriminator="type"),
]


class ToolShellEnvironmentContainerAuto(BaseModel):
    type: Literal["container_auto"]
    """Automatically creates a container for this request"""

    file_ids: Optional[List[str]] = None
    """An optional list of uploaded files to make available to your code."""

    memory_limit: Optional[Literal["1g", "4g", "16g", "64g"]] = None
    """The memory limit for the container."""

    network_policy: Optional[ToolShellEnvironmentContainerAutoNetworkPolicy] = None
    """Network access policy for the container."""

    skills: Optional[List[ToolShellEnvironmentContainerAutoSkill]] = None
    """An optional list of skills referenced by id or inline data."""


class ToolShellEnvironmentContainerReference(BaseModel):
    container_id: str
    """The ID of the referenced container."""

    type: Literal["container_reference"]
    """References a container created with the /v1/containers endpoint"""


class ToolShellEnvironmentLocalSkill(BaseModel):
    description: str
    """The description of the skill."""

    name: str
    """The name of the skill."""

    path: str
    """The path to the directory containing the skill."""


class ToolShellEnvironmentLocal(BaseModel):
    type: Literal["local"]
    """Use a local computer environment."""

    skills: Optional[List[ToolShellEnvironmentLocalSkill]] = None
    """An optional list of skills."""


ToolShellEnvironment: TypeAlias = Annotated[
    Union[ToolShellEnvironmentContainerAuto, ToolShellEnvironmentContainerReference, ToolShellEnvironmentLocal, None],
    PropertyInfo(discriminator="type"),
]


class ToolShell(BaseModel):
    """A Responses shell tool.

    Use a hosted container or return local shell results with response.item.create. Domain secrets are not supported.
    """

    type: Literal["shell"]

    environment: Optional[ToolShellEnvironment] = None


class ToolImageGeneration(BaseModel):
    type: Literal["image_generation"]


class ToolMcp(BaseModel):
    type: Literal["mcp"]


class ToolCustom(BaseModel):
    type: Literal["custom"]


class ToolNamespace(BaseModel):
    type: Literal["namespace"]


class ToolSearch(BaseModel):
    type: Literal["tool_search"]


class ToolProgrammaticToolCalling(BaseModel):
    type: Literal["programmatic_tool_calling"]


class ToolComputer(BaseModel):
    type: Literal["computer"]


class ToolApplyPatch(BaseModel):
    type: Literal["apply_patch"]


Tool: TypeAlias = Annotated[
    Union[
        FunctionTool,
        ToolWebSearch,
        ToolFileSearch,
        ToolCodeInterpreter,
        ToolShell,
        ToolImageGeneration,
        ToolMcp,
        ToolCustom,
        ToolNamespace,
        ToolSearch,
        ToolProgrammaticToolCalling,
        ToolComputer,
        ToolApplyPatch,
    ],
    PropertyInfo(discriminator="type"),
]


class ResponsesDelegationUpdateConfig(BaseModel):
    """Updates to the Responses backend of an existing Live session.

    Omitted settings retain their current values.
    """

    instructions: Optional[str] = None
    """Instructions for the delegated Responses model, separate from Live instructions.

    See
    [backend prompting](https://developers.openai.com/api/docs/guides/live-delegation#start-with-your-existing-backend-prompt).
    """

    max_output_tokens: Optional[int] = None
    """Maximum number of output tokens for each delegated response."""

    model: Optional[str] = None
    """The Responses backend model to use for subsequent delegated requests.

    Omit to keep the current backend model.
    """

    parallel_tool_calls: Optional[bool] = None
    """
    Whether the delegated Responses model may request multiple tool calls in a
    single response.
    """

    reasoning: Optional[Reasoning] = None
    """Reasoning settings passed to each delegated Responses request."""

    service_tier: Optional[Literal["auto", "default", "fast_tier_temp_pilot", "flex", "priority", "ultrafast"]] = None
    """Service tier for delegated Responses requests."""

    text: Optional[Text] = None
    """Text generation settings passed to each delegated Responses request."""

    tool_choice: Union[Literal["auto", "none", "required"], Dict[str, object], None] = None
    """
    Controls which tool the Responses backend uses when handling a task delegated by
    the Live model.
    """

    tools: Optional[List[Tool]] = None
    """
    Tools available to the Responses backend while it handles tasks delegated by the
    Live model.
    """
