# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from typing import List, Union, Optional
from typing_extensions import Literal, Annotated, TypeAlias

from ..._utils import PropertyInfo
from ..._models import BaseModel
from .function_tool import FunctionTool

__all__ = [
    "ResponsesDelegationConfig",
    "Reasoning",
    "Text",
    "ToolChoice",
    "ToolChoiceLiveFunctionToolChoiceParam",
    "ToolChoiceLiveMCPToolChoiceParam",
    "Tool",
    "ToolWebSearch",
]


class Reasoning(BaseModel):
    """Reasoning settings passed to each delegated Responses request."""

    effort: Optional[Literal["none", "minimal", "low", "medium", "high", "xhigh"]] = None
    """How much reasoning effort the delegated Responses model should use.

    Supported values depend on the backend model.
    """

    summary: Optional[Literal["concise", "detailed", "auto"]] = None
    """
    The reasoning summary to request from the delegated Responses model, when
    supported.
    """


class Text(BaseModel):
    """Text generation settings passed to each delegated Responses request."""

    verbosity: Optional[Literal["low", "medium", "high"]] = None
    """The amount of detail in text generated by the Responses backend.

    This does not configure the Live model’s spoken delivery.
    """


class ToolChoiceLiveFunctionToolChoiceParam(BaseModel):
    name: str

    type: Literal["function"]


class ToolChoiceLiveMCPToolChoiceParam(BaseModel):
    name: str

    server_label: str

    type: Literal["mcp"]


ToolChoice: TypeAlias = Union[
    Literal["auto", "none", "required"], ToolChoiceLiveFunctionToolChoiceParam, ToolChoiceLiveMCPToolChoiceParam
]


class ToolWebSearch(BaseModel):
    """A web search tool available to the Live session’s Responses backend."""

    type: Literal["web_search"]
    """The tool type. Always `web_search`."""


Tool: TypeAlias = Annotated[Union[FunctionTool, ToolWebSearch], PropertyInfo(discriminator="type")]


class ResponsesDelegationConfig(BaseModel):
    """
    Model, prompt, and tool settings for tasks delegated by the Live session to a Responses backend.
    """

    model: str
    """The model used for server-owned Responses delegations."""

    instructions: Optional[str] = None
    """Instructions for the delegated Responses model, separate from Live instructions.

    See
    [backend prompting](https://developers.openai.com/api/docs/guides/live-delegation#start-with-your-existing-backend-prompt).
    """

    max_output_tokens: Optional[int] = None
    """Maximum number of output tokens for each delegated response."""

    parallel_tool_calls: Optional[bool] = None
    """
    Whether the delegated Responses model may request multiple tool calls in a
    single response.
    """

    reasoning: Optional[Reasoning] = None
    """Reasoning settings passed to each delegated Responses request."""

    service_tier: Optional[Literal["auto", "default", "fast_tier_temp_pilot", "flex", "priority", "ultrafast"]] = None
    """Service tier for delegated Responses requests."""

    text: Optional[Text] = None
    """Text generation settings passed to each delegated Responses request."""

    tool_choice: Optional[ToolChoice] = None
    """
    Controls which tool the Responses backend uses when handling a task delegated by
    the Live model.
    """

    tools: Optional[List[Tool]] = None
    """
    Tools available to the Responses backend while it handles tasks delegated by the
    Live model.
    """
