# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Dict, Union, Iterable, Optional
from typing_extensions import Literal, Required, TypeAlias, TypedDict

from .function_tool_param import FunctionToolParam

__all__ = [
    "ResponsesDelegationConfigParam",
    "Reasoning",
    "Text",
    "ToolChoice",
    "ToolChoiceLiveFunctionToolChoiceParam",
    "ToolChoiceLiveMCPToolChoiceParam",
    "Tool",
    "ToolWebSearch",
    "ToolFileSearch",
    "ToolCodeInterpreter",
    "ToolShell",
    "ToolImageGeneration",
]


class Reasoning(TypedDict, total=False):
    """Reasoning settings passed to each delegated Responses request."""

    effort: Optional[Literal["none", "minimal", "low", "medium", "high", "xhigh"]]
    """How much reasoning effort the delegated Responses model should use.

    Supported values depend on the backend model.
    """

    summary: Optional[Literal["concise", "detailed", "auto"]]
    """
    The reasoning summary to request from the delegated Responses model, when
    supported.
    """


class Text(TypedDict, total=False):
    """Text generation settings passed to each delegated Responses request."""

    verbosity: Optional[Literal["low", "medium", "high"]]
    """The amount of detail in text generated by the Responses backend.

    This does not configure the Live model’s spoken delivery.
    """


class ToolChoiceLiveFunctionToolChoiceParam(TypedDict, total=False):
    name: Required[str]

    type: Required[Literal["function"]]


class ToolChoiceLiveMCPToolChoiceParam(TypedDict, total=False):
    name: Required[str]

    server_label: Required[str]

    type: Required[Literal["mcp"]]


ToolChoice: TypeAlias = Union[
    Literal["auto", "none", "required"], ToolChoiceLiveFunctionToolChoiceParam, ToolChoiceLiveMCPToolChoiceParam
]


class ToolWebSearch(TypedDict, total=False):
    """A web search tool available to the Live session’s Responses backend."""

    type: Required[Literal["web_search"]]
    """The tool type. Always `web_search`."""


class ToolFileSearch(TypedDict, total=False):
    type: Required[Literal["file_search"]]


class ToolCodeInterpreter(TypedDict, total=False):
    type: Required[Literal["code_interpreter"]]


class ToolShell(TypedDict, total=False):
    """A Responses shell tool with a container_auto or container_reference environment.

    Local execution and domain secrets are not supported.
    """

    environment: Required[Dict[str, object]]

    type: Required[Literal["shell"]]


class ToolImageGeneration(TypedDict, total=False):
    type: Required[Literal["image_generation"]]


Tool: TypeAlias = Union[
    FunctionToolParam, ToolWebSearch, ToolFileSearch, ToolCodeInterpreter, ToolShell, ToolImageGeneration
]


class ResponsesDelegationConfigParam(TypedDict, total=False):
    """
    Model, prompt, and tool settings for tasks delegated by the Live session to a Responses backend.
    """

    model: Required[str]
    """The model used for server-owned Responses delegations."""

    instructions: Optional[str]
    """Instructions for the delegated Responses model, separate from Live instructions.

    See
    [backend prompting](https://developers.openai.com/api/docs/guides/live-delegation#start-with-your-existing-backend-prompt).
    """

    max_output_tokens: Optional[int]
    """Maximum number of output tokens for each delegated response."""

    parallel_tool_calls: Optional[bool]
    """
    Whether the delegated Responses model may request multiple tool calls in a
    single response.
    """

    reasoning: Optional[Reasoning]
    """Reasoning settings passed to each delegated Responses request."""

    service_tier: Optional[Literal["auto", "default", "fast_tier_temp_pilot", "flex", "priority", "ultrafast"]]
    """Service tier for delegated Responses requests."""

    text: Optional[Text]
    """Text generation settings passed to each delegated Responses request."""

    tool_choice: ToolChoice
    """
    Controls which tool the Responses backend uses when handling a task delegated by
    the Live model.
    """

    tools: Iterable[Tool]
    """
    Tools available to the Responses backend while it handles tasks delegated by the
    Live model.
    """
