# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Dict, Union, Iterable, Optional
from typing_extensions import Literal, Required, TypeAlias, TypedDict

from ..._types import SequenceNotStr
from .function_tool_param import FunctionToolParam

__all__ = [
    "ResponsesDelegationUpdateConfigParam",
    "Reasoning",
    "Text",
    "Tool",
    "ToolWebSearch",
    "ToolFileSearch",
    "ToolCodeInterpreter",
    "ToolShell",
    "ToolShellEnvironment",
    "ToolShellEnvironmentContainerAuto",
    "ToolShellEnvironmentContainerAutoNetworkPolicy",
    "ToolShellEnvironmentContainerAutoNetworkPolicyDisabled",
    "ToolShellEnvironmentContainerAutoNetworkPolicyAllowlist",
    "ToolShellEnvironmentContainerAutoSkill",
    "ToolShellEnvironmentContainerAutoSkillSkillReference",
    "ToolShellEnvironmentContainerAutoSkillInline",
    "ToolShellEnvironmentContainerAutoSkillInlineSource",
    "ToolShellEnvironmentContainerReference",
    "ToolShellEnvironmentLocal",
    "ToolShellEnvironmentLocalSkill",
    "ToolImageGeneration",
    "ToolMcp",
    "ToolCustom",
    "ToolNamespace",
    "ToolSearch",
    "ToolProgrammaticToolCalling",
    "ToolComputer",
    "ToolApplyPatch",
]


class Reasoning(TypedDict, total=False):
    """Reasoning settings passed to each delegated Responses request."""

    effort: Optional[Literal["none", "minimal", "low", "medium", "high", "xhigh"]]
    """How much reasoning effort the delegated Responses model should use.

    Supported values depend on the backend model.
    """

    summary: Optional[Literal["concise", "detailed", "auto"]]
    """
    The reasoning summary to request from the delegated Responses model, when
    supported.
    """


class Text(TypedDict, total=False):
    """Text generation settings passed to each delegated Responses request."""

    verbosity: Optional[Literal["low", "medium", "high"]]
    """The amount of detail in text generated by the Responses backend.

    This does not configure the Live model’s spoken delivery.
    """


class ToolWebSearch(TypedDict, total=False):
    """A web search tool available to the Live session’s Responses backend."""

    type: Required[Literal["web_search"]]
    """The tool type. Always `web_search`."""


class ToolFileSearch(TypedDict, total=False):
    type: Required[Literal["file_search"]]


class ToolCodeInterpreter(TypedDict, total=False):
    type: Required[Literal["code_interpreter"]]


class ToolShellEnvironmentContainerAutoNetworkPolicyDisabled(TypedDict, total=False):
    type: Required[Literal["disabled"]]
    """Disable outbound network access. Always `disabled`."""


class ToolShellEnvironmentContainerAutoNetworkPolicyAllowlist(TypedDict, total=False):
    allowed_domains: Required[SequenceNotStr[str]]
    """A list of allowed domains when type is `allowlist`."""

    type: Required[Literal["allowlist"]]
    """Allow outbound network access only to specified domains. Always `allowlist`."""


ToolShellEnvironmentContainerAutoNetworkPolicy: TypeAlias = Union[
    ToolShellEnvironmentContainerAutoNetworkPolicyDisabled, ToolShellEnvironmentContainerAutoNetworkPolicyAllowlist
]


class ToolShellEnvironmentContainerAutoSkillSkillReference(TypedDict, total=False):
    skill_id: Required[str]
    """The ID of the referenced skill."""

    type: Required[Literal["skill_reference"]]
    """References a skill created with the /v1/skills endpoint."""

    version: Optional[str]
    """Optional skill version. Use a positive integer or 'latest'. Omit for default."""


class ToolShellEnvironmentContainerAutoSkillInlineSource(TypedDict, total=False):
    """Inline skill payload"""

    data: Required[str]
    """Base64-encoded skill zip bundle."""

    media_type: Required[Literal["application/zip"]]
    """The media type of the inline skill payload. Must be `application/zip`."""

    type: Required[Literal["base64"]]
    """The type of the inline skill source. Must be `base64`."""


class ToolShellEnvironmentContainerAutoSkillInline(TypedDict, total=False):
    description: Required[str]
    """The description of the skill."""

    name: Required[str]
    """The name of the skill."""

    source: Required[ToolShellEnvironmentContainerAutoSkillInlineSource]
    """Inline skill payload"""

    type: Required[Literal["inline"]]
    """Defines an inline skill for this request."""


ToolShellEnvironmentContainerAutoSkill: TypeAlias = Union[
    ToolShellEnvironmentContainerAutoSkillSkillReference, ToolShellEnvironmentContainerAutoSkillInline
]


class ToolShellEnvironmentContainerAuto(TypedDict, total=False):
    type: Required[Literal["container_auto"]]
    """Automatically creates a container for this request"""

    file_ids: Optional[SequenceNotStr[str]]
    """An optional list of uploaded files to make available to your code."""

    memory_limit: Optional[Literal["1g", "4g", "16g", "64g"]]
    """The memory limit for the container."""

    network_policy: Optional[ToolShellEnvironmentContainerAutoNetworkPolicy]
    """Network access policy for the container."""

    skills: Optional[Iterable[ToolShellEnvironmentContainerAutoSkill]]
    """An optional list of skills referenced by id or inline data."""


class ToolShellEnvironmentContainerReference(TypedDict, total=False):
    container_id: Required[str]
    """The ID of the referenced container."""

    type: Required[Literal["container_reference"]]
    """References a container created with the /v1/containers endpoint"""


class ToolShellEnvironmentLocalSkill(TypedDict, total=False):
    description: Required[str]
    """The description of the skill."""

    name: Required[str]
    """The name of the skill."""

    path: Required[str]
    """The path to the directory containing the skill."""


class ToolShellEnvironmentLocal(TypedDict, total=False):
    type: Required[Literal["local"]]
    """Use a local computer environment."""

    skills: Optional[Iterable[ToolShellEnvironmentLocalSkill]]
    """An optional list of skills."""


ToolShellEnvironment: TypeAlias = Union[
    ToolShellEnvironmentContainerAuto, ToolShellEnvironmentContainerReference, ToolShellEnvironmentLocal
]


class ToolShell(TypedDict, total=False):
    """A Responses shell tool.

    Use a hosted container or return local shell results with response.item.create. Domain secrets are not supported.
    """

    type: Required[Literal["shell"]]

    environment: Optional[ToolShellEnvironment]


class ToolImageGeneration(TypedDict, total=False):
    type: Required[Literal["image_generation"]]


class ToolMcp(TypedDict, total=False):
    type: Required[Literal["mcp"]]


class ToolCustom(TypedDict, total=False):
    type: Required[Literal["custom"]]


class ToolNamespace(TypedDict, total=False):
    type: Required[Literal["namespace"]]


class ToolSearch(TypedDict, total=False):
    type: Required[Literal["tool_search"]]


class ToolProgrammaticToolCalling(TypedDict, total=False):
    type: Required[Literal["programmatic_tool_calling"]]


class ToolComputer(TypedDict, total=False):
    type: Required[Literal["computer"]]


class ToolApplyPatch(TypedDict, total=False):
    type: Required[Literal["apply_patch"]]


Tool: TypeAlias = Union[
    FunctionToolParam,
    ToolWebSearch,
    ToolFileSearch,
    ToolCodeInterpreter,
    ToolShell,
    ToolImageGeneration,
    ToolMcp,
    ToolCustom,
    ToolNamespace,
    ToolSearch,
    ToolProgrammaticToolCalling,
    ToolComputer,
    ToolApplyPatch,
]


class ResponsesDelegationUpdateConfigParam(TypedDict, total=False):
    """Updates to the Responses backend of an existing Live session.

    Omitted settings retain their current values.
    """

    instructions: Optional[str]
    """Instructions for the delegated Responses model, separate from Live instructions.

    See
    [backend prompting](https://developers.openai.com/api/docs/guides/live-delegation#start-with-your-existing-backend-prompt).
    """

    max_output_tokens: Optional[int]
    """Maximum number of output tokens for each delegated response."""

    model: str
    """The Responses backend model to use for subsequent delegated requests.

    Omit to keep the current backend model.
    """

    parallel_tool_calls: Optional[bool]
    """
    Whether the delegated Responses model may request multiple tool calls in a
    single response.
    """

    reasoning: Optional[Reasoning]
    """Reasoning settings passed to each delegated Responses request."""

    service_tier: Optional[Literal["auto", "default", "fast_tier_temp_pilot", "flex", "priority", "ultrafast"]]
    """Service tier for delegated Responses requests."""

    text: Optional[Text]
    """Text generation settings passed to each delegated Responses request."""

    tool_choice: Union[Literal["auto", "none", "required"], Dict[str, object]]
    """
    Controls which tool the Responses backend uses when handling a task delegated by
    the Live model.
    """

    tools: Iterable[Tool]
    """
    Tools available to the Responses backend while it handles tasks delegated by the
    Live model.
    """
