# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Union, Iterable, Optional
from typing_extensions import Literal, Required, TypeAlias, TypedDict

from .built_in_voice import BuiltInVoice
from .audio_format_param import AudioFormatParam
from .custom_voice_param import CustomVoiceParam
from .initial_item_param import InitialItemParam
from .client_config_param import ClientConfigParam
from .client_delegation_param import ClientDelegationParam
from .responses_delegation_config_param import ResponsesDelegationConfigParam

__all__ = ["SessionConfigParam", "Audio", "AudioOutput", "AudioOutputVoice", "Delegation", "DelegationResponses"]

AudioOutputVoice: TypeAlias = Union[str, BuiltInVoice, CustomVoiceParam]


class AudioOutput(TypedDict, total=False):
    """The voice used for speech generated by the Live model."""

    voice: AudioOutputVoice
    """
    The voice used for Live speech, as a built-in voice name or a custom voice
    object containing its ID. Defaults to `marin` and cannot change after startup.
    """


class Audio(TypedDict, total=False):
    """Startup audio configuration.

    Only primary WebSockets accept audio.format; WebRTC and SIP negotiate their media format. Voice and format are immutable after startup.
    """

    format: AudioFormatParam
    """
    Audio encoding and sample rate for audio sent and received over a Live WebSocket
    connection. WebRTC and SIP negotiate their media format separately.
    """

    output: AudioOutput
    """The voice used for speech generated by the Live model."""


class DelegationResponses(TypedDict, total=False):
    """Delegate tasks to a Responses model managed by the Live session."""

    responses: Required[ResponsesDelegationConfigParam]
    """
    Backend model, prompt, and tools used when the Live session delegates a task to
    Responses.
    """

    type: Required[Literal["responses"]]
    """The delegation owner.

    Always `responses` for tasks handled by the Responses API.
    """


Delegation: TypeAlias = Union[ClientDelegationParam, DelegationResponses]


class SessionConfigParam(TypedDict, total=False):
    """
    Initial configuration for a Live session, including its model, conversation instructions, audio, and delegated task handling.
    """

    model: Required[Union[str, Literal["gpt-live-1"]]]
    """The Live model.

    Required in the session configuration for every transport; do not pass it as a
    URL query parameter.
    """

    audio: Audio
    """Startup audio configuration.

    Only primary WebSockets accept audio.format; WebRTC and SIP negotiate their
    media format. Voice and format are immutable after startup.
    """

    client: ClientConfigParam
    """
    Startup-only capabilities for an untrusted frontend attached to a unified WebRTC
    session. Trusted sideband connections are unaffected.
    """

    delegation: Optional[Delegation]
    """Who handles tasks delegated by the Live model.

    Omitted or null selects your application; use `responses` to let the API manage
    a Responses backend.
    """

    input: Iterable[InitialItemParam]
    """Ordered text-only history supplied before startup.

    Supports developer, user, and assistant messages with one text part each; at
    most 128 messages and 8,192 rendered tokens in total.
    """

    instructions: Optional[str]
    """
    Frontend instructions for voice, conversation, interruptions, and when to
    delegate. Start with the
    [Live prompting guide](https://developers.openai.com/api/docs/guides/live-prompting);
    put business rules and tool workflows in a separate
    [backend prompt](https://developers.openai.com/api/docs/guides/live-delegation#start-with-your-existing-backend-prompt).
    Limited to 16,384 client-supplied tokens. Omitted or blank instructions use
    server defaults. Immutable after startup.
    """

    store: bool
    """Whether to store the session for later forking and recording download.

    Defaults to false for new sessions.
    """
