# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from typing import List, Union, Optional
from typing_extensions import Literal, Annotated, TypeAlias

from ..._utils import PropertyInfo
from ..._models import BaseModel
from .audio_format import AudioFormat
from .custom_voice import CustomVoice
from .initial_item import InitialItem
from .client_config import ClientConfig
from .built_in_voice import BuiltInVoice
from .client_delegation import ClientDelegation
from .responses_delegation_config import ResponsesDelegationConfig

__all__ = ["SessionConfig", "Audio", "AudioOutput", "AudioOutputVoice", "Delegation", "DelegationResponses"]

AudioOutputVoice: TypeAlias = Union[str, BuiltInVoice, CustomVoice]


class AudioOutput(BaseModel):
    """The voice used for speech generated by the Live model."""

    voice: Optional[AudioOutputVoice] = None
    """
    The voice used for Live speech, as a built-in voice name or a custom voice
    object containing its ID. Defaults to `marin` and cannot change after startup.
    """


class Audio(BaseModel):
    """Startup audio configuration.

    Only primary WebSockets accept audio.format; WebRTC and SIP negotiate their media format. Voice and format are immutable after startup.
    """

    format: Optional[AudioFormat] = None
    """
    Audio encoding and sample rate for audio sent and received over a Live WebSocket
    connection. WebRTC and SIP negotiate their media format separately.
    """

    output: Optional[AudioOutput] = None
    """The voice used for speech generated by the Live model."""


class DelegationResponses(BaseModel):
    """Delegate tasks to a Responses model managed by the Live session."""

    responses: ResponsesDelegationConfig
    """
    Backend model, prompt, and tools used when the Live session delegates a task to
    Responses.
    """

    type: Literal["responses"]
    """The delegation owner.

    Always `responses` for tasks handled by the Responses API.
    """


Delegation: TypeAlias = Annotated[
    Union[ClientDelegation, DelegationResponses, None], PropertyInfo(discriminator="type")
]


class SessionConfig(BaseModel):
    """
    Initial configuration for a Live session, including its model, conversation instructions, audio, and delegated task handling.
    """

    model: Union[str, Literal["gpt-live-1"]]
    """The Live model.

    Required in the session configuration for every transport; do not pass it as a
    URL query parameter.
    """

    audio: Optional[Audio] = None
    """Startup audio configuration.

    Only primary WebSockets accept audio.format; WebRTC and SIP negotiate their
    media format. Voice and format are immutable after startup.
    """

    client: Optional[ClientConfig] = None
    """
    Startup-only capabilities for an untrusted frontend attached to a unified WebRTC
    session. Trusted sideband connections are unaffected.
    """

    delegation: Optional[Delegation] = None
    """Who handles tasks delegated by the Live model.

    Omitted or null selects your application; use `responses` to let the API manage
    a Responses backend.
    """

    input: Optional[List[InitialItem]] = None
    """Ordered text-only history supplied before startup.

    Supports developer, user, and assistant messages with one text part each; at
    most 128 messages and 8,192 rendered tokens in total.
    """

    instructions: Optional[str] = None
    """
    Frontend instructions for voice, conversation, interruptions, and when to
    delegate. Start with the
    [Live prompting guide](https://developers.openai.com/api/docs/guides/live-prompting);
    put business rules and tool workflows in a separate
    [backend prompt](https://developers.openai.com/api/docs/guides/live-delegation#start-with-your-existing-backend-prompt).
    Limited to 16,384 client-supplied tokens. Omitted or blank instructions use
    server defaults. Immutable after startup.
    """

    store: Optional[bool] = None
    """Whether to store the session for later forking and recording download.

    Defaults to false for new sessions.
    """
