# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Union, Iterable, Optional
from typing_extensions import Literal, Required, TypeAlias, TypedDict

from .built_in_voice import BuiltInVoice
from .custom_voice_param import CustomVoiceParam
from .initial_item_param import InitialItemParam
from .client_delegation_param import ClientDelegationParam
from .responses_delegation_config_param import ResponsesDelegationConfigParam

__all__ = [
    "SessionAcceptParams",
    "Session",
    "SessionAudio",
    "SessionAudioOutput",
    "SessionAudioOutputVoice",
    "SessionDelegation",
    "SessionDelegationResponses",
]


class SessionAcceptParams(TypedDict, total=False):
    session: Required[Session]
    """
    Model and startup configuration for the Live session that answers the incoming
    SIP call.
    """


SessionAudioOutputVoice: TypeAlias = Union[str, BuiltInVoice, CustomVoiceParam]


class SessionAudioOutput(TypedDict, total=False):
    """Settings for speech generated by the Live model.

    Choose the voice before starting the session.
    """

    voice: SessionAudioOutputVoice
    """
    The voice used for Live speech, as a built-in voice name or a custom voice
    object containing its ID. Defaults to `marin` and cannot change after startup.
    """


class SessionAudio(TypedDict, total=False):
    """Startup audio output configuration.

    SIP negotiates the media format; audio.format is only accepted for primary WebSockets. Voice cannot change after startup.
    """

    output: SessionAudioOutput
    """Settings for speech generated by the Live model.

    Choose the voice before starting the session.
    """


class SessionDelegationResponses(TypedDict, total=False):
    """Delegate tasks to a Responses model managed by the Live session."""

    responses: Required[ResponsesDelegationConfigParam]
    """
    Backend model, prompt, and tools used when the Live session delegates a task to
    Responses.
    """

    type: Required[Literal["responses"]]
    """The delegation owner.

    Always `responses` for tasks handled by the Responses API.
    """


SessionDelegation: TypeAlias = Union[ClientDelegationParam, SessionDelegationResponses]


class Session(TypedDict, total=False):
    """
    Model and startup configuration for the Live session that answers the incoming SIP call.
    """

    model: Required[Union[str, Literal["gpt-live-1"]]]
    """The Live model to use for the accepted call."""

    type: Required[Literal["live"]]
    """The session type. Always `live`."""

    audio: SessionAudio
    """Startup audio output configuration.

    SIP negotiates the media format; audio.format is only accepted for primary
    WebSockets. Voice cannot change after startup.
    """

    delegation: Optional[SessionDelegation]
    """Who handles tasks delegated by the Live model.

    Omitted or null selects your application; use `responses` to let the API manage
    a Responses backend.
    """

    input: Iterable[InitialItemParam]
    """Ordered text-only history supplied before startup.

    Supports developer, user, and assistant messages with one text part each; at
    most 128 messages and 8,192 rendered tokens in total.
    """

    instructions: Optional[str]
    """
    Frontend instructions for voice, conversation, interruptions, and when to
    delegate. Start with the
    [Live prompting guide](https://developers.openai.com/api/docs/guides/live-prompting);
    put business rules and tool workflows in a separate
    [backend prompt](https://developers.openai.com/api/docs/guides/live-delegation#start-with-your-existing-backend-prompt).
    Limited to 16,384 client-supplied tokens. Omitted or blank instructions use
    server defaults. Immutable after startup.
    """

    store: bool
    """Whether to store the session for later forking and recording download.

    Defaults to false for new sessions.
    """
