# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional
from typing_extensions import Literal

from .tool import Tool
from ..._models import BaseModel

__all__ = ["ResponseToolSearchOutputItem"]


class ResponseToolSearchOutputItem(BaseModel):
    id: str
    """The unique ID of the tool search output item."""

    call_id: Optional[str] = None
    """The unique ID of the tool search call generated by the model."""

    execution: Literal["server", "client"]
    """Whether tool search was executed by the server or by the client."""

    status: Literal["in_progress", "completed", "incomplete"]
    """The status of the tool search output item that was recorded."""

    tools: List[Tool]
    """The loaded tool definitions returned by tool search."""

    type: Literal["tool_search_output"]
    """The type of the item. Always `tool_search_output`."""

    created_by: Optional[str] = None
    """The identifier of the actor that created the item."""
