# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Any, Dict, List, Optional
from typing_extensions import Literal

from .tool import Tool
from ..._models import BaseModel

__all__ = ["ResponseToolSearchOutputItem"]


class ResponseToolSearchOutputItem(BaseModel):
    id: str
    """The unique ID of the tool search output item."""

    call_id: Optional[str] = None
    """The unique ID of the tool search call generated by the model."""

    execution: Literal["server", "client"]
    """Whether tool search was executed by the server or by the client."""

    status: Literal["in_progress", "completed", "incomplete"]
    """The status of the tool search output item that was recorded."""

    tools: List[Tool]
    """The loaded tool definitions returned by tool search."""

    type: Literal["tool_search_output"]
    """The type of the item. Always `tool_search_output`."""

    created_by: Optional[str] = None
    """The identifier of the actor that created the item."""

    def as_input(self) -> Dict[str, Any]:
        """Return a dict representation of this item suitable for use as input in a subsequent response.

        Strips output-only fields (``created_by``) that the API does not accept as input.
        """
        data = self.to_dict()
        data.pop("created_by", None)
        return data
