# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Dict, Union, Iterable, Optional
from typing_extensions import Literal, Required, TypedDict

from ...._types import SequenceNotStr
from ..agent_text_param import AgentTextParam
from ..agent_tool_param import AgentToolParam
from ..environment_param import EnvironmentParam
from ..agent_reasoning_param import AgentReasoningParam
from ..multi_agent_config_param import MultiAgentConfigParam
from ..agent_session_input_message_param import AgentSessionInputMessageParam

__all__ = ["SessionCreateParamsBase", "Agent", "SessionCreateParamsNonStreaming", "SessionCreateParamsStreaming"]


class SessionCreateParamsBase(TypedDict, total=False):
    environment: Required[EnvironmentParam]
    """An inline execution environment or a reference to an environment template."""

    agent: Agent
    """Agent configuration.

    With `agent_id`, supplied fields override the saved agent for this session.
    Without `agent_id`, `model` is required.
    """

    agent_id: str
    """The ID of a saved reusable agent.

    Omit `agent` to use its configuration unchanged.
    """

    input: Union[str, Iterable[AgentSessionInputMessageParam], None]
    """Initial input submitted when creating a session."""

    metadata: Optional[Dict[str, str]]
    """
    Up to 16 string key-value pairs, with keys up to 64 and values up to 512
    characters. Omission or null defaults to an empty map.
    """

    vault_ids: Optional[SequenceNotStr[str]]
    """The IDs of vaults made available to the session."""


class Agent(TypedDict, total=False):
    """Agent configuration.

    With `agent_id`, supplied fields override the saved agent for this session. Without `agent_id`, `model` is required.
    """

    instructions: Optional[str]
    """Additional instructions appended to the agent's default base instructions.

    Omit to leave unchanged.
    """

    model: str
    """The model to use for the agent. The requested model name is preserved."""

    multi_agent: Optional[MultiAgentConfigParam]
    """Explicit configuration for creating and coordinating subagents."""

    reasoning: Optional[AgentReasoningParam]
    """Reasoning configuration for the agent."""

    service_tier: Optional[Literal["auto", "default", "flex", "priority", "fast"]]
    """The service tier used for model requests.

    - `auto` - Selects the service tier automatically.
    - `default` - Uses the default service tier.
    - `flex` - Uses the flex service tier.
    - `priority` - Uses the priority service tier.
    - `fast` - Uses the fast service tier.
    """

    text: Optional[AgentTextParam]
    """Configuration for text generated by the agent."""

    tools: Optional[Iterable[AgentToolParam]]
    """Tools available to the agent. Omit to inherit, or pass null to clear them."""


class SessionCreateParamsNonStreaming(SessionCreateParamsBase, total=False):
    stream: Literal[False]
    """Whether to stream session events as server-sent events. Defaults to `false`."""


class SessionCreateParamsStreaming(SessionCreateParamsBase):
    stream: Required[Literal[True]]
    """Whether to stream session events as server-sent events. Defaults to `false`."""


SessionCreateParams = Union[SessionCreateParamsNonStreaming, SessionCreateParamsStreaming]
