# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from typing import Dict, List, Union, Optional
from typing_extensions import Literal, Annotated, TypeAlias

from ..._utils import PropertyInfo
from ..._models import BaseModel
from .agent_text import AgentText
from .agent_tool import AgentTool
from .environment import Environment
from .token_usage import TokenUsage
from .agent_reasoning import AgentReasoning
from .multi_agent_config import MultiAgentConfig

__all__ = [
    "AgentSession",
    "Agent",
    "RequiredAction",
    "RequiredActionSessionRequiredActionResourceFunctionCall",
    "RequiredActionSessionRequiredActionResourceEnvironmentConnection",
]


class Agent(BaseModel):
    """The agent running in the session."""

    id: str
    """The ID of the agent."""

    instructions: Optional[str] = None
    """Custom instructions appended to the agent's default base instructions."""

    model: str
    """The model used by the agent."""

    multi_agent: MultiAgentConfig
    """Configuration for creating and coordinating subagents."""

    name: Optional[str] = None
    """
    The reusable agent's name when the session was created, or null if no name was
    saved. Later changes to the agent's name do not affect this value.
    """

    reasoning: AgentReasoning
    """The agent's reasoning configuration."""

    service_tier: Literal["auto", "default", "flex", "priority", "fast"]
    """The effective service-tier policy for model requests. Defaults to `auto`."""

    text: AgentText
    """Configuration for text generated by the agent."""

    tools: List[AgentTool]
    """Tools available to the agent."""


class RequiredActionSessionRequiredActionResourceFunctionCall(BaseModel):
    """Run a function tool and submit its result."""

    arguments: object
    """The arguments supplied by the model."""

    call_id: str
    """The ID to include when submitting the function result."""

    name: str
    """The function name."""

    turn_id: str
    """The ID of the turn that requested the function call."""

    type: Literal["function_call"]
    """The type of the object. Always `function_call`."""


class RequiredActionSessionRequiredActionResourceEnvironmentConnection(BaseModel):
    """Reconnect a session environment."""

    environment_id: str
    """The ID of the environment to reconnect."""

    type: Literal["environment_connection"]
    """The type of the object. Always `environment_connection`."""


RequiredAction: TypeAlias = Annotated[
    Union[
        RequiredActionSessionRequiredActionResourceFunctionCall,
        RequiredActionSessionRequiredActionResourceEnvironmentConnection,
    ],
    PropertyInfo(discriminator="type"),
]


class AgentSession(BaseModel):
    """A Managed Agents session."""

    id: str
    """The ID of the session."""

    agent: Agent
    """The agent running in the session."""

    created_at: int
    """The Unix timestamp, in seconds, when the session was created."""

    environment: Environment
    """The execution environment for the session."""

    error: Optional[str] = None
    """The error that caused the session to fail, if any."""

    last_active_at: int
    """The Unix timestamp, in seconds, when the session was last active."""

    metadata: Dict[str, str]
    """Custom string key-value pairs attached to the session."""

    object: Literal["agent.session"]
    """The object type. Always `agent.session`."""

    required_actions: List[RequiredAction]
    """Actions that must be completed before the session can continue."""

    status: Literal["idle", "in_progress", "requires_action", "failed"]
    """The current status of the session.

    - `idle` - The session has no turn in progress and is ready for input. A hosted
      environment may still be provisioning.
    - `in_progress` - The session is processing a turn.
    - `requires_action` - The session is waiting for one or more required actions.
    - `failed` - The session failed.
    """

    usage: Optional[TokenUsage] = None
    """Recorded token usage for a session or turn.

    Usage is best effort and may change.
    """

    vault_ids: List[str]
    """The IDs of vaults made available to the session."""
