# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Optional
from typing_extensions import Literal, TypedDict

from .text_format_param import TextFormatParam

__all__ = ["AgentTextParam"]


class AgentTextParam(TypedDict, total=False):
    """Configuration for text generated by the agent."""

    format: Optional[TextFormatParam]
    """The output format. Omission uses ordinary text (`{"type": "text"}`)."""

    verbosity: Optional[Literal["low", "medium", "high"]]
    """The amount of text the model should produce.

    Defaults to `medium`, matching Responses.

    - `low` - Produces less text.
    - `medium` - Uses the default amount of text.
    - `high` - Produces more text.
    """
