# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Dict, Iterable, Optional
from typing_extensions import Literal, Required, TypedDict

from .agent_text_param import AgentTextParam
from .agent_reasoning_param import AgentReasoningParam
from .multi_agent_config_param import MultiAgentConfigParam
from .persisted_agent_tool_param import PersistedAgentToolParam

__all__ = ["AgentCreateParams"]


class AgentCreateParams(TypedDict, total=False):
    model: Required[str]
    """The model to use for the agent. The requested model name is preserved."""

    instructions: Optional[str]
    """Additional instructions appended to the agent's default base instructions.

    Omit or set to null to add no custom instructions.
    """

    metadata: Optional[Dict[str, str]]
    """
    Up to 16 string key-value pairs, with keys up to 64 and values up to 512
    characters. Omission or null defaults to an empty map.
    """

    multi_agent: Optional[MultiAgentConfigParam]
    """Explicit configuration for creating and coordinating subagents."""

    name: Optional[str]
    """A human-readable name for the agent. Omission or null leaves the agent unnamed."""

    reasoning: Optional[AgentReasoningParam]
    """Reasoning configuration for the agent."""

    service_tier: Optional[Literal["auto", "default", "flex", "priority", "fast"]]
    """The service tier used for model requests.

    - `auto` - Selects the service tier automatically.
    - `default` - Uses the default service tier.
    - `flex` - Uses the flex service tier.
    - `priority` - Uses the priority service tier.
    - `fast` - Uses the fast service tier.
    """

    text: Optional[AgentTextParam]
    """Configuration for text generated by the agent."""

    tools: Optional[Iterable[PersistedAgentToolParam]]
    """Tools available to the agent. Defaults to an empty list."""
