# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Dict, Iterable, Optional
from typing_extensions import Literal, TypedDict

from .agent_text_param import AgentTextParam
from .agent_reasoning_param import AgentReasoningParam
from .multi_agent_config_param import MultiAgentConfigParam
from .persisted_agent_tool_param import PersistedAgentToolParam

__all__ = ["AgentUpdateParams"]


class AgentUpdateParams(TypedDict, total=False):
    instructions: Optional[str]
    """Additional instructions appended to the agent's default base instructions.

    Omit to leave unchanged.
    """

    metadata: Optional[Dict[str, str]]
    """Replaces all metadata.

    Omit to leave unchanged, or pass null or {} to clear it. Up to 16 string
    key-value pairs, with keys up to 64 and values up to 512 characters.
    """

    model: str
    """The model to use for the agent. The requested model name is preserved."""

    multi_agent: Optional[MultiAgentConfigParam]
    """Explicit configuration for creating and coordinating subagents."""

    name: Optional[str]
    """A replacement name. Omit to leave unchanged, or pass null to clear it."""

    reasoning: Optional[AgentReasoningParam]
    """Reasoning configuration for the agent."""

    service_tier: Optional[Literal["auto", "default", "flex", "priority", "fast"]]
    """The service tier used for model requests.

    - `auto` - Selects the service tier automatically.
    - `default` - Uses the default service tier.
    - `flex` - Uses the flex service tier.
    - `priority` - Uses the priority service tier.
    - `fast` - Uses the fast service tier.
    """

    text: Optional[AgentTextParam]
    """Configuration for text generated by the agent."""

    tools: Optional[Iterable[PersistedAgentToolParam]]
    """Tools available to the agent."""
