# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from typing import List, Union, Optional
from typing_extensions import Literal, Annotated, TypeAlias

from ..._utils import PropertyInfo
from ..._models import BaseModel
from .beta_response_steer_input_content import BetaResponseSteerInputContent
from .beta_response_function_call_output_item_list import BetaResponseFunctionCallOutputItemList

__all__ = [
    "BetaResponseSteerInput",
    "ResponseSteerInputItemList",
    "ResponseSteerInputItemListMessage",
    "ResponseSteerInputItemListMessageAgent",
    "ResponseSteerInputItemListFunctionCallOutput",
    "ResponseSteerInputItemListFunctionCallOutputAgent",
    "ResponseSteerInputItemListFunctionCallOutputCaller",
    "ResponseSteerInputItemListFunctionCallOutputCallerDirect",
    "ResponseSteerInputItemListFunctionCallOutputCallerProgram",
]


class ResponseSteerInputItemListMessageAgent(BaseModel):
    """The agent that produced this item."""

    agent_name: str
    """The canonical name of the agent that produced this item."""


class ResponseSteerInputItemListMessage(BaseModel):
    content: Union[List[BetaResponseSteerInputContent], str]
    """The message content, as an array of content parts."""

    role: Literal["user"]
    """The message role. Always `user`."""

    type: Literal["message"]
    """The item type. Always `message`."""

    id: Optional[str] = None
    """The unique ID of this message item."""

    agent: Optional[ResponseSteerInputItemListMessageAgent] = None
    """The agent that produced this item."""

    status: Optional[str] = None
    """The status of the message item."""


class ResponseSteerInputItemListFunctionCallOutputAgent(BaseModel):
    """The agent that produced this item."""

    agent_name: str
    """The canonical name of the agent that produced this item."""


class ResponseSteerInputItemListFunctionCallOutputCallerDirect(BaseModel):
    type: Literal["direct"]
    """The caller type. Always `direct`."""


class ResponseSteerInputItemListFunctionCallOutputCallerProgram(BaseModel):
    caller_id: str
    """The call ID of the program item that produced this tool call."""

    type: Literal["program"]
    """The caller type. Always `program`."""


ResponseSteerInputItemListFunctionCallOutputCaller: TypeAlias = Annotated[
    Union[
        ResponseSteerInputItemListFunctionCallOutputCallerDirect,
        ResponseSteerInputItemListFunctionCallOutputCallerProgram,
        None,
    ],
    PropertyInfo(discriminator="type"),
]


class ResponseSteerInputItemListFunctionCallOutput(BaseModel):
    """The output of a function tool call."""

    output: Union[str, BetaResponseFunctionCallOutputItemList]
    """Text, image, or file output of the function tool call."""

    type: Literal["function_call_output"]
    """The type of the function tool call output. Always `function_call_output`."""

    id: Optional[str] = None
    """The unique ID of the function tool call output.

    Populated when this item is returned via API.
    """

    agent: Optional[ResponseSteerInputItemListFunctionCallOutputAgent] = None
    """The agent that produced this item."""

    call_id: Optional[str] = None
    """The unique ID of the function tool call generated by the model."""

    caller: Optional[ResponseSteerInputItemListFunctionCallOutputCaller] = None
    """The execution context that produced this tool call."""

    name: Optional[str] = None
    """The name of the tool that produced the output."""

    namespace: Optional[str] = None
    """The namespace of the tool that produced the output."""

    status: Optional[Literal["in_progress", "completed", "incomplete"]] = None
    """The status of the item.

    One of `in_progress`, `completed`, or `incomplete`. Populated when items are
    returned via API.
    """


ResponseSteerInputItemList: TypeAlias = Annotated[
    Union[ResponseSteerInputItemListMessage, ResponseSteerInputItemListFunctionCallOutput],
    PropertyInfo(discriminator="type"),
]

BetaResponseSteerInput: TypeAlias = Union[str, List[ResponseSteerInputItemList]]
