# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Union, Iterable, Optional
from typing_extensions import Literal, Required, TypeAlias, TypedDict

from .beta_response_steer_input_content_param import BetaResponseSteerInputContentParam
from .beta_response_function_call_output_item_list_param import BetaResponseFunctionCallOutputItemListParam

__all__ = [
    "BetaResponseSteerInputParam",
    "ResponseSteerInputItemList",
    "ResponseSteerInputItemListMessage",
    "ResponseSteerInputItemListMessageAgent",
    "ResponseSteerInputItemListFunctionCallOutput",
    "ResponseSteerInputItemListFunctionCallOutputAgent",
    "ResponseSteerInputItemListFunctionCallOutputCaller",
    "ResponseSteerInputItemListFunctionCallOutputCallerDirect",
    "ResponseSteerInputItemListFunctionCallOutputCallerProgram",
]


class ResponseSteerInputItemListMessageAgent(TypedDict, total=False):
    """The agent that produced this item."""

    agent_name: Required[str]
    """The canonical name of the agent that produced this item."""


class ResponseSteerInputItemListMessage(TypedDict, total=False):
    content: Required[Union[Iterable[BetaResponseSteerInputContentParam], str]]
    """The message content, as an array of content parts."""

    role: Required[Literal["user"]]
    """The message role. Always `user`."""

    type: Required[Literal["message"]]
    """The item type. Always `message`."""

    id: Optional[str]
    """The unique ID of this message item."""

    agent: Optional[ResponseSteerInputItemListMessageAgent]
    """The agent that produced this item."""

    status: Optional[str]
    """The status of the message item."""


class ResponseSteerInputItemListFunctionCallOutputAgent(TypedDict, total=False):
    """The agent that produced this item."""

    agent_name: Required[str]
    """The canonical name of the agent that produced this item."""


class ResponseSteerInputItemListFunctionCallOutputCallerDirect(TypedDict, total=False):
    type: Required[Literal["direct"]]
    """The caller type. Always `direct`."""


class ResponseSteerInputItemListFunctionCallOutputCallerProgram(TypedDict, total=False):
    caller_id: Required[str]
    """The call ID of the program item that produced this tool call."""

    type: Required[Literal["program"]]
    """The caller type. Always `program`."""


ResponseSteerInputItemListFunctionCallOutputCaller: TypeAlias = Union[
    ResponseSteerInputItemListFunctionCallOutputCallerDirect, ResponseSteerInputItemListFunctionCallOutputCallerProgram
]


class ResponseSteerInputItemListFunctionCallOutput(TypedDict, total=False):
    """The output of a function tool call."""

    output: Required[Union[str, BetaResponseFunctionCallOutputItemListParam]]
    """Text, image, or file output of the function tool call."""

    type: Required[Literal["function_call_output"]]
    """The type of the function tool call output. Always `function_call_output`."""

    id: Optional[str]
    """The unique ID of the function tool call output.

    Populated when this item is returned via API.
    """

    agent: Optional[ResponseSteerInputItemListFunctionCallOutputAgent]
    """The agent that produced this item."""

    call_id: Optional[str]
    """The unique ID of the function tool call generated by the model."""

    caller: Optional[ResponseSteerInputItemListFunctionCallOutputCaller]
    """The execution context that produced this tool call."""

    name: Optional[str]
    """The name of the tool that produced the output."""

    namespace: Optional[str]
    """The namespace of the tool that produced the output."""

    status: Optional[Literal["in_progress", "completed", "incomplete"]]
    """The status of the item.

    One of `in_progress`, `completed`, or `incomplete`. Populated when items are
    returned via API.
    """


ResponseSteerInputItemList: TypeAlias = Union[
    ResponseSteerInputItemListMessage, ResponseSteerInputItemListFunctionCallOutput
]

BetaResponseSteerInputParam: TypeAlias = Union[str, Iterable[ResponseSteerInputItemList]]
