# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import List, Optional
from typing_extensions import Literal

from ..._models import BaseModel
from .beta_tool import BetaTool

__all__ = ["BetaResponseToolSearchOutputItem", "Agent"]


class Agent(BaseModel):
    """The agent that produced this item."""

    agent_name: str
    """The canonical name of the agent that produced this item."""


class BetaResponseToolSearchOutputItem(BaseModel):
    id: str
    """The unique ID of the tool search output item."""

    call_id: Optional[str] = None
    """The unique ID of the tool search call generated by the model."""

    execution: Literal["server", "client"]
    """Whether tool search was executed by the server or by the client."""

    status: Literal["in_progress", "completed", "incomplete"]
    """The status of the tool search output item that was recorded."""

    tools: List[BetaTool]
    """The loaded tool definitions returned by tool search."""

    type: Literal["tool_search_output"]
    """The type of the item. Always `tool_search_output`."""

    agent: Optional[Agent] = None
    """The agent that produced this item."""

    created_by: Optional[str] = None
    """The identifier of the actor that created the item."""
