# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from typing import Optional
from typing_extensions import Literal

from ..._models import BaseModel

__all__ = ["BetaResponseCompactionItemParam", "Agent"]


class Agent(BaseModel):
    """The agent that produced this item."""

    agent_name: str
    """The canonical name of the agent that produced this item."""


class BetaResponseCompactionItemParam(BaseModel):
    """
    A compaction item generated by the [`v1/responses/compact` API](https://platform.openai.com/docs/api-reference/responses/compact).
    """

    encrypted_content: str
    """The encrypted content of the compaction summary."""

    type: Literal["compaction"]
    """The type of the item. Always `compaction`."""

    id: Optional[str] = None
    """The ID of the compaction item."""

    agent: Optional[Agent] = None
    """The agent that produced this item."""
