# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from ..._models import BaseModel

__all__ = ["TokenUsage", "InputTokensDetails", "OutputTokensDetails"]


class InputTokensDetails(BaseModel):
    """A breakdown of the agent's input token usage."""

    cached_tokens: int
    """The number of input tokens retrieved from the prompt cache."""


class OutputTokensDetails(BaseModel):
    """A breakdown of the agent's output token usage."""

    reasoning_tokens: int
    """The number of output tokens used for reasoning."""


class TokenUsage(BaseModel):
    """Recorded token usage for a session or turn.

    Usage is best effort and may change.
    """

    input_tokens: int
    """The number of input tokens used by the agent."""

    input_tokens_details: InputTokensDetails
    """A breakdown of the agent's input token usage."""

    output_tokens: int
    """The number of output tokens generated by the agent."""

    output_tokens_details: OutputTokensDetails
    """A breakdown of the agent's output token usage."""

    total_tokens: int
    """The total number of input and output tokens used by the agent."""
