# Hand-written module (NOT generated by Stainless).
#
# Centralises every piece of httpx2 knowledge behind the optional `httpx2` extra so
# that `_base_client.py` needs only tiny, codegen-friendly substitutions. httpx2 is
# Pydantic's maintained fork of httpx; it is a *separate* library (its own client,
# exception hierarchy and Response), so classic-httpx `isinstance`/`except` checks do
# not see it and must be widened to the tuples defined here.
#
# The module imports cleanly whether or not httpx2 is installed. When it is absent,
# the type tuples collapse to the classic-httpx entries (zero behaviour change) and
# `DefaultHttpx2Client` becomes a stub that raises a helpful error, mirroring the
# accepted `DefaultAioHttpClient` pattern.
from __future__ import annotations

from typing import TYPE_CHECKING, Any, cast

import httpx

from ._constants import DEFAULT_TIMEOUT, DEFAULT_CONNECTION_LIMITS

try:
    import httpx2  # type: ignore[import-not-found]  # pyright: ignore[reportMissingImports]
except ImportError:
    httpx2 = None  # type: ignore[assignment]


__all__ = [
    "DefaultHttpx2Client",
    "DefaultAsyncHttpx2Client",
    "SYNC_HTTP_CLIENT_TYPES",
    "ASYNC_HTTP_CLIENT_TYPES",
    "SYNC_HTTP_CLIENT_NAMES",
    "ASYNC_HTTP_CLIENT_NAMES",
    "TIMEOUT_EXCEPTIONS",
    "HTTP_STATUS_ERRORS",
    "STREAM_CONSUMED_ERRORS",
    "REQUEST_NOT_READ_ERRORS",
    "HTTPX2_DEFAULT_TIMEOUT",
    "coerce_httpx2_request_url",
    "noop_auth_for",
]

_NOT_INSTALLED_MESSAGE = "To use the httpx2 client you must have installed the package with the `httpx2` extra"


if TYPE_CHECKING:
    # What the type checker (targeting py3.9, where httpx2 is not installable) sees.
    # The runtime values below additionally include the httpx2 equivalents when the
    # extra is present; the classic-httpx types here keep `err.response` et al. resolving
    # to httpx.* at the `except`/`isinstance` call sites in `_base_client.py`.
    SYNC_HTTP_CLIENT_TYPES: tuple[type[httpx.Client], ...] = (httpx.Client,)
    ASYNC_HTTP_CLIENT_TYPES: tuple[type[httpx.AsyncClient], ...] = (httpx.AsyncClient,)
    TIMEOUT_EXCEPTIONS: tuple[type[httpx.TimeoutException], ...] = (httpx.TimeoutException,)
    HTTP_STATUS_ERRORS: tuple[type[httpx.HTTPStatusError], ...] = (httpx.HTTPStatusError,)
    STREAM_CONSUMED_ERRORS: tuple[type[httpx.StreamConsumed], ...] = (httpx.StreamConsumed,)
    REQUEST_NOT_READ_ERRORS: tuple[type[httpx.RequestNotRead], ...] = (httpx.RequestNotRead,)

    # Human-readable names of the accepted client types, for `TypeError` messages in
    # `_base_client.py` (mentions httpx2 only when the extra is actually importable).
    SYNC_HTTP_CLIENT_NAMES: str = "`httpx.Client`"
    ASYNC_HTTP_CLIENT_NAMES: str = "`httpx.AsyncClient`"

    # Sentinel for the cross-class default-timeout comparison in `_base_client.py`
    # (a bare httpx2 client reports httpx2's 5s default, which is `!=` the classic
    # default and must not be mistaken for a user-supplied timeout). `None` when the
    # extra is absent, so the extra comparison is a harmless no-op.
    HTTPX2_DEFAULT_TIMEOUT: httpx.Timeout | None = None

    _HTTPX2_CLIENT_TYPES: tuple[type[Any], ...] = ()
    _HTTPX2_AUTH_CLASS: type[Any] | None = None

    # Aliased to httpx.* for type checking, exactly like `DefaultAioHttpClient`. The
    # real runtime classes are defined below.
    DefaultHttpx2Client = httpx.Client
    DefaultAsyncHttpx2Client = httpx.AsyncClient
elif httpx2 is None:
    SYNC_HTTP_CLIENT_TYPES = (httpx.Client,)
    ASYNC_HTTP_CLIENT_TYPES = (httpx.AsyncClient,)
    TIMEOUT_EXCEPTIONS = (httpx.TimeoutException,)
    HTTP_STATUS_ERRORS = (httpx.HTTPStatusError,)
    STREAM_CONSUMED_ERRORS = (httpx.StreamConsumed,)
    REQUEST_NOT_READ_ERRORS = (httpx.RequestNotRead,)
    SYNC_HTTP_CLIENT_NAMES = "`httpx.Client`"
    ASYNC_HTTP_CLIENT_NAMES = "`httpx.AsyncClient`"
    HTTPX2_DEFAULT_TIMEOUT = None
    _HTTPX2_CLIENT_TYPES = ()
    _HTTPX2_AUTH_CLASS = None

    class DefaultHttpx2Client(httpx.Client):
        def __init__(self, **_kwargs: Any) -> None:
            raise RuntimeError(_NOT_INSTALLED_MESSAGE)

    class DefaultAsyncHttpx2Client(httpx.AsyncClient):
        def __init__(self, **_kwargs: Any) -> None:
            raise RuntimeError(_NOT_INSTALLED_MESSAGE)
else:
    # Funnel every httpx2 attribute access through a single `Any` alias so the module
    # type-checks with httpx2 absent (its types are unresolved on the py3.9 lint env).
    _h2: Any = httpx2

    SYNC_HTTP_CLIENT_TYPES = (httpx.Client, _h2.Client)
    ASYNC_HTTP_CLIENT_TYPES = (httpx.AsyncClient, _h2.AsyncClient)
    TIMEOUT_EXCEPTIONS = (httpx.TimeoutException, _h2.TimeoutException)
    HTTP_STATUS_ERRORS = (httpx.HTTPStatusError, _h2.HTTPStatusError)
    STREAM_CONSUMED_ERRORS = (httpx.StreamConsumed, _h2.StreamConsumed)
    REQUEST_NOT_READ_ERRORS = (httpx.RequestNotRead, _h2.RequestNotRead)
    SYNC_HTTP_CLIENT_NAMES = "`httpx.Client` or `httpx2.Client`"
    ASYNC_HTTP_CLIENT_NAMES = "`httpx.AsyncClient` or `httpx2.AsyncClient`"
    _HTTPX2_CLIENT_TYPES = (_h2.Client, _h2.AsyncClient)
    _HTTPX2_AUTH_CLASS = _h2.Auth

    try:
        HTTPX2_DEFAULT_TIMEOUT = _h2._config.DEFAULT_TIMEOUT_CONFIG
    except AttributeError:  # pragma: no cover - defensive, tracks httpx's own fallback
        HTTPX2_DEFAULT_TIMEOUT = _h2.Timeout(5.0)

    def _httpx2_timeout() -> Any:
        # Rebuild the SDK defaults natively: httpx2's client rejects a classic
        # `httpx.Timeout` at construction (though `build_request` accepts one).
        return _h2.Timeout(
            connect=DEFAULT_TIMEOUT.connect,
            read=DEFAULT_TIMEOUT.read,
            write=DEFAULT_TIMEOUT.write,
            pool=DEFAULT_TIMEOUT.pool,
        )

    def _httpx2_limits() -> Any:
        return _h2.Limits(
            max_connections=DEFAULT_CONNECTION_LIMITS.max_connections,
            max_keepalive_connections=DEFAULT_CONNECTION_LIMITS.max_keepalive_connections,
        )

    class DefaultHttpx2Client(_h2.Client):
        def __init__(self, **kwargs: Any) -> None:
            kwargs.setdefault("timeout", _httpx2_timeout())
            kwargs.setdefault("limits", _httpx2_limits())
            kwargs.setdefault("follow_redirects", True)
            super().__init__(**kwargs)

    class DefaultAsyncHttpx2Client(_h2.AsyncClient):
        def __init__(self, **kwargs: Any) -> None:
            kwargs.setdefault("timeout", _httpx2_timeout())
            kwargs.setdefault("limits", _httpx2_limits())
            kwargs.setdefault("follow_redirects", True)
            super().__init__(**kwargs)


def coerce_httpx2_request_url(client: httpx.Client | httpx.AsyncClient, url: httpx.URL) -> httpx.URL | str:
    """httpx2's ``build_request`` rejects a classic ``httpx.URL`` (``Expected str or
    httpx2.URL``), so hand it a ``str`` when the underlying client is an httpx2 one.
    Classic httpx clients keep the ``httpx.URL`` unchanged (no behaviour change)."""
    if _HTTPX2_CLIENT_TYPES and isinstance(client, _HTTPX2_CLIENT_TYPES):
        return str(url)
    return url


def noop_auth_for(client: httpx.Client | httpx.AsyncClient) -> httpx.Auth:
    """A no-op ``Auth`` matched to the client's backend. The SDK passes a bare
    ``httpx.Auth()`` to ``send()`` for provider-managed clients (the real auth headers
    are applied by the provider's request hooks), but httpx2's ``send`` rejects a
    classic ``httpx.Auth`` instance (``Invalid "auth" argument``), so httpx2 clients
    must be handed an ``httpx2.Auth()`` instead."""
    if _HTTPX2_AUTH_CLASS is not None and isinstance(client, _HTTPX2_CLIENT_TYPES):
        return cast("httpx.Auth", _HTTPX2_AUTH_CLASS())
    return httpx.Auth()
