#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ] && [ "$SKIP_BREW" != "1" ] && [ -t 0 ]; then
  brew bundle check >/dev/null 2>&1 || {
    echo -n "==> Install Homebrew dependencies? (y/N): "
    read -r response
    case "$response" in
      [yY][eE][sS]|[yY])
        brew bundle
        ;;
      *)
        ;;
    esac
    echo
  }
fi

echo "==> Installing Python dependencies…"

# experimental uv support makes installations significantly faster
rye config --set-bool behavior.use-uv=true

rye sync --all-features
