#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Running formatters"
uv run ruff format
uv run python scripts/utils/ruffen-docs.py README.md $(find . -type f -name api.md)
uv run ruff check --fix .
uv run ruff format
