#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

if [ "$1" = "--fix" ]; then
  echo "==> Running lints with --fix"
  rye run fix:ruff
else
  echo "==> Running lints"
  rye run lint
fi

echo "==> Making sure it imports"
rye run python -c 'import openai'
