# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Union, Optional
from typing_extensions import Literal, Required, TypedDict

from .image_model import ImageModel

__all__ = ["ImageGenerateParamsBase", "ImageGenerateParamsNonStreaming", "ImageGenerateParamsStreaming"]


class ImageGenerateParamsBase(TypedDict, total=False):
    prompt: Required[str]
    """A text description of the desired image(s).

    The maximum length is 32000 characters for the GPT image models. Legacy limits
    for the retired models were 1000 characters for `dall-e-2` and 4000 characters
    for `dall-e-3`.
    """

    background: Optional[Literal["transparent", "opaque", "auto"]]
    """Allows to set transparency for the background of the generated image(s).

    Must be one of `transparent`, `opaque`, or `auto` (default value). When `auto`
    is used, the model will automatically determine the best background for the
    image.

    `gpt-image-2.5-sunburst` and `gpt-image-2.5-flare`, including their `2026-09-08`
    snapshots, support `opaque` and `transparent` backgrounds. Transparent
    backgrounds are available for supported GPT Image models. For `gpt-image-2` and
    `gpt-image-2-2026-04-21`, this support is in preview. When using `transparent`,
    set the output format to `png` or `webp`.
    """

    model: Union[str, ImageModel, None]
    """The GPT Image model to use for image generation.

    Specify a supported model explicitly, such as `gpt-image-1`, `gpt-image-1-mini`,
    `gpt-image-1.5`, `gpt-image-2`, `gpt-image-2-2026-04-21`,
    `gpt-image-2.5-sunburst`, `gpt-image-2.5-sunburst-2026-09-08`,
    `gpt-image-2.5-flare`, or `gpt-image-2.5-flare-2026-09-08`. DALL·E 2
    (`dall-e-2`) and DALL·E 3 (`dall-e-3`) were retired from the API on May 12,
    2026; see [deprecations](https://developers.openai.com/api/docs/deprecations).
    """

    moderation: Optional[Literal["low", "auto"]]
    """
    Control the content-moderation level for images generated by the GPT image
    models. Must be either `low` for less restrictive filtering or `auto` (default
    value).
    """

    n: Optional[int]
    """The number of images to generate.

    Must be between 1 and 10. The retired `dall-e-3` model only supported `n=1`.
    """

    output_compression: Optional[int]
    """The compression level (0-100%) for the generated images.

    This parameter is only supported for the GPT image models with the `webp` or
    `jpeg` output formats, and defaults to 100.
    """

    output_format: Optional[Literal["png", "jpeg", "webp"]]
    """The format in which the generated images are returned.

    This parameter is only supported for the GPT image models. Must be one of `png`,
    `jpeg`, or `webp`.
    """

    partial_images: Optional[int]
    """The number of partial images to generate.

    This parameter is used for streaming responses that return partial images. Value
    must be between 0 and 3. When set to 0, the response will be a single image sent
    in one streaming event.

    Note that the final image may be sent before the full number of partial images
    are generated if the full image is generated more quickly.
    """

    quality: Optional[Literal["standard", "hd", "low", "medium", "high", "xhigh", "max", "auto"]]
    """The quality of the image that will be generated.

    - `auto` (default value) will automatically select the best quality for the
      given model.
    - `high`, `medium` and `low` are supported for the GPT image models.
    - `gpt-image-2.5-sunburst` and `gpt-image-2.5-flare`, including their
      `2026-09-08` snapshots, also support `xhigh` and `max`.
    - The retired `dall-e-3` model supported the legacy values `hd` and `standard`.
    - The retired `dall-e-2` model only supported the legacy value `standard`.
    """

    response_format: Optional[Literal["url", "b64_json"]]
    """
    Legacy response format: `url` or `b64_json`, for the retired `dall-e-2` and
    `dall-e-3` models. Returned URLs were valid for 60 minutes after image
    generation. This parameter is not supported for the GPT image models, which
    always return base64-encoded images.
    """

    size: Union[
        str,
        Literal["auto", "1024x1024", "1536x1024", "1024x1536", "256x256", "512x512", "1792x1024", "1024x1792"],
        None,
    ]
    """The size of the generated images.

    For `gpt-image-2`, `gpt-image-2-2026-04-21`, `gpt-image-2.5-sunburst`,
    `gpt-image-2.5-sunburst-2026-09-08`, `gpt-image-2.5-flare`, and
    `gpt-image-2.5-flare-2026-09-08`, arbitrary resolutions are supported as
    `WIDTHxHEIGHT` strings, for example `1536x864`. Width and height must both be
    divisible by 16 and the requested aspect ratio must be between 1:3 and 3:1.
    Resolutions above `2560x1440` are experimental, and the maximum supported
    resolution is `3840x2160`. The requested size must also satisfy the model's
    current pixel and edge limits. The standard sizes `1024x1024`, `1536x1024`, and
    `1024x1536` are supported by the GPT image models; `auto` is supported for
    models that allow automatic sizing. Legacy sizes for the retired `dall-e-2`
    model were `256x256`, `512x512`, and `1024x1024`. Legacy sizes for the retired
    `dall-e-3` model were `1024x1024`, `1792x1024`, and `1024x1792`.
    """

    style: Optional[Literal["vivid", "natural"]]
    """Legacy style options `vivid` and `natural` for the retired `dall-e-3` model.

    Vivid produced hyper-real and dramatic images; natural produced more natural,
    less hyper-real looking images. This parameter is not supported for the GPT
    image models.
    """

    user: str
    """
    A unique identifier representing your end-user, which can help OpenAI to monitor
    and detect abuse.
    [Learn more](https://developers.openai.com/api/docs/guides/safety-best-practices#implement-safety-identifiers).
    """


class ImageGenerateParamsNonStreaming(ImageGenerateParamsBase, total=False):
    stream: Optional[Literal[False]]
    """Generate the image in streaming mode.

    Defaults to `false`. See the
    [Image generation guide](https://developers.openai.com/api/docs/guides/image-generation)
    for more information. This parameter is only supported for the GPT image models.
    """


class ImageGenerateParamsStreaming(ImageGenerateParamsBase):
    stream: Required[Literal[True]]
    """Generate the image in streaming mode.

    Defaults to `false`. See the
    [Image generation guide](https://developers.openai.com/api/docs/guides/image-generation)
    for more information. This parameter is only supported for the GPT image models.
    """


ImageGenerateParams = Union[ImageGenerateParamsNonStreaming, ImageGenerateParamsStreaming]
