# File generated from our OpenAPI spec by Castiron. See CONTRIBUTING.md for details.

from typing import Optional

from .._models import BaseModel

__all__ = ["Image"]


class Image(BaseModel):
    """Represents the content or the URL of an image generated by the OpenAI API."""

    b64_json: Optional[str] = None
    """The base64-encoded image data.

    Returned by default for the GPT image models. For the retired `dall-e-2` and
    `dall-e-3` models, this field was present only when `response_format` was set to
    `b64_json`.
    """

    revised_prompt: Optional[str] = None
    """
    Legacy field for the retired `dall-e-3` model: the revised prompt that was used
    to generate the image.
    """

    url: Optional[str] = None
    """
    Legacy field for the retired `dall-e-2` and `dall-e-3` models: the URL of the
    generated image when `response_format` was set to `url`, the legacy default.
    Unsupported for the GPT image models.
    """
