name: Create releases
on:
  schedule:
    - cron: '0 5 * * *' # every day at 5am UTC
  push:
    branches:
      - main

jobs:
  release:
    name: release
    if: github.ref == 'refs/heads/main' && github.repository == 'openai/openai-python'
    runs-on: ubuntu-latest
    environment: publish

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: stainless-api/trigger-release-please@bb6677c5a04578eec1ccfd9e1913b5b78ed64c61 # v1
        id: release
        with:
          repo: ${{ github.event.repository.full_name }}
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

      - name: Set up uv
        if: ${{ steps.release.outputs.releases_created }}
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # setup-uv v8.1.0; uv 0.11.7
        with:
          version: "0.11.7"
          enable-cache: true

      - name: Set up Python
        if: ${{ steps.release.outputs.releases_created }}
        run: uv python install

      - name: Build
        if: ${{ steps.release.outputs.releases_created }}
        run: uv build

      - name: Publish to PyPI
        if: ${{ steps.release.outputs.releases_created }}
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.OPENAI_PYPI_TOKEN || secrets.PYPI_TOKEN }}
